export type Screen = 'main' | 'tanks' | 'loading' | 'external' | 'selection';

export interface ScadaData {
    tank1_temp: number;
    tank2_temp: number;
    acid_flow_instant: number;
    acid_flow_total: number;
    waste_flow_instant: number;
    waste_flow_total: number;
    hcl_tank1_level: number;
    hcl_tank2_level: number;
    hcl_tank3_level: number;
    hcl_tank4_level: number;
    hcl_tank5_level: number;
    h2so4_tank1_level: number;
    leak1: number;
    leak2: number;
    leak3: number;
    leak4: number;
    loading_instant: number;
    loading_total: number;
    old_fan_v: number;
    old_pump1_v: number;
    old_pump2_v: number;
    old_pump3_v: number;
    drum_fan_v: number;
    drum_pump1_v: number;
    drum_pump2_v: number;
    drum_centrifuge_v: number;
    w3_underground1_temp: number;
    w3_underground2_temp: number;
    w3_underground3_temp: number;
    w3_iron1_temp: number;
    w3_iron2_temp: number;
    w3_iron1_pressure: number;
    w3_iron2_pressure: number;
    w3_iron1_current: number;
    w3_iron2_current: number;
    w3_glass1_temp: number;
    w3_glass2_temp: number;
    w3_glass3_temp: number;
    w3_glass4_temp: number;
    w3_glass5_temp: number;
    w3_glass1_current: number;
    w3_glass2_current: number;
    w3_glass3_current: number;
    w3_glass4_current: number;
    w3_glass5_current: number;
    w3_enamel1_temp: number;
    w3_enamel2_temp: number;
    w3_enamel3_temp: number;
    w3_enamel4_temp: number;
    w3_enamel5_temp: number;
    w3_enamel6_temp: number;
    w3_enamel1_pressure: number;
    w3_enamel2_pressure: number;
    w3_enamel3_pressure: number;
    w3_enamel4_pressure: number;
    w3_enamel5_pressure: number;
    w3_enamel6_pressure: number;
    w3_enamel1_current: number;
    w3_enamel2_current: number;
    w3_enamel3_current: number;
    w3_enamel4_current: number;
    w3_enamel5_current: number;
    w3_enamel6_current: number;
    w3_poly_tail_fan_v: number;
    w3_poly_tail_pump1_v: number;
    w3_poly_tail_pump2_v: number;
    w3_lowiron_tail_fan_v: number;
    w3_lowiron_tail_pump1_v: number;
    w3_lowiron_tail_pump2_v: number;
    w3_steam_instant: number;
    w3_steam_total: number;
    w3_lowiron_steam_instant: number;
    w3_lowiron_steam_total: number;
    w3_loading_instant: number;
    w3_loading_total: number;
    w3_alkali_instant: number;
    w3_alkali_total: number;
    w3_iron_flow_instant: number;
    w3_iron_flow_total: number;
    w3_hcl_flow_instant: number;
    w3_hcl_flow_total: number;
    w4_reactor1_temp: number;
    w4_reactor2_temp: number;
    w4_reactor3_temp: number;
    w4_reactor4_temp: number;
    w4_reactor5_temp: number;
    w4_reactor6_temp: number;
    w4_reactor1_pressure: number;
    w4_reactor2_pressure: number;
    w4_reactor3_pressure: number;
    w4_reactor4_pressure: number;
    w4_reactor5_pressure: number;
    w4_reactor6_pressure: number;
    w4_reactor1_current: number;
    w4_reactor2_current: number;
    w4_reactor3_current: number;
    w4_reactor4_current: number;
    w4_reactor5_current: number;
    w4_reactor6_current: number;
    w4_fubang_khs_instant: number;
    w4_fubang_khs_total: number;
    w4_fubang_hcl_instant: number;
    w4_fubang_hcl_total: number;
    w4_output_packaging: number;
    w5_reactor1_temp: number;
    w5_reactor2_temp: number;
    w5_reactor3_temp: number;
    w5_reactor4_temp: number;
    w5_reactor5_temp: number;
    w5_reactor6_temp: number;
    w5_reactor1_pressure: number;
    w5_reactor2_pressure: number;
    w5_reactor3_pressure: number;
    w5_reactor4_pressure: number;
    w5_reactor5_pressure: number;
    w5_reactor6_pressure: number;
    w5_reactor1_current: number;
    w5_reactor2_current: number;
    w5_reactor3_current: number;
    w5_reactor4_current: number;
    w5_reactor5_current: number;
    w5_reactor6_current: number;
    w5_output1: number;
    w5_output2: number;
    w6_dilute_sulfuric_level: number;
    w6_sulfuric1_level: number;
    w6_sulfuric2_level: number;
    w6_sulfuric3_level: number;
    w6_sulfuric4_level: number;
    w6_sulfuric5_level: number;
    w6_sulfuric6_level: number;
    w6_sulfuric7_level: number;
    w6_hcl1_level: number;
    w6_hcl2_level: number;
    w6_underground_level: number;
    w6_kettle1_pressure: number;
    w6_kettle2_pressure: number;
    w6_kettle3_pressure: number;
    w6_kettle4_pressure: number;
    w6_kettle1_temp: number;
    w6_kettle2_temp: number;
    w6_kettle3_temp: number;
    w6_kettle4_temp: number;
    w6_kettle1_oxygen_flow: number;
    w6_kettle2_oxygen_flow: number;
    w6_kettle3_oxygen_flow: number;
    w6_kettle4_oxygen_flow: number;
    w6_loading1_instant: number;
    w6_loading1_total: number;
    w6_loading2_instant: number;
    w6_loading2_total: number;
    w6_batch1_instant: number;
    w6_batch1_total: number;
    w6_batch2_instant: number;
    w6_batch2_total: number;
    w6_loading1_once: number;
    w6_loading2_once: number;
    w6_batch1_once: number;
    w6_batch2_once: number;
    w6_kettle1_link_feed_open: number;
    w6_kettle1_link_feed_closed: number;
    w6_kettle2_link_feed_open: number;
    w6_kettle2_link_feed_closed: number;
    w6_kettle3_link_feed_open: number;
    w6_kettle3_link_feed_closed: number;
    w6_kettle4_link_feed_open: number;
    w6_kettle4_link_feed_closed: number;
    w6_kettle1_feed_open: number;
    w6_kettle1_feed_closed: number;
    w6_kettle2_feed_open: number;
    w6_kettle2_feed_closed: number;
    w6_kettle3_feed_open: number;
    w6_kettle3_feed_closed: number;
    w6_kettle4_feed_open: number;
    w6_kettle4_feed_closed: number;
    w6_kettle1_discharge_open: number;
    w6_kettle1_discharge_closed: number;
    w6_kettle2_discharge_open: number;
    w6_kettle2_discharge_closed: number;
    w6_kettle3_discharge_open: number;
    w6_kettle3_discharge_closed: number;
    w6_kettle4_discharge_open: number;
    w6_kettle4_discharge_closed: number;
    w6_kettle1_catalyst_open: number;
    w6_kettle1_catalyst_closed: number;
    w6_kettle2_catalyst_open: number;
    w6_kettle2_catalyst_closed: number;
    w6_kettle3_catalyst_open: number;
    w6_kettle3_catalyst_closed: number;
    w6_kettle4_catalyst_open: number;
    w6_kettle4_catalyst_closed: number;
    w6_kettle1_oxygen_open: number;
    w6_kettle2_oxygen_open: number;
    w6_kettle3_oxygen_open: number;
    w6_kettle4_oxygen_open: number;
    w7_reactor1_temp: number;
    w7_reactor2_temp: number;
    w7_reactor3_temp: number;
    w7_reactor4_temp: number;
    w7_reactor5_temp: number;
    w7_reactor6_temp: number;
    w7_reactor7_temp: number;
    w7_reactor8_temp: number;
    w7_reactor9_temp: number;
    w7_reactor10_temp: number;
    w7_reactor1_pressure: number;
    w7_reactor2_pressure: number;
    w7_reactor3_pressure: number;
    w7_reactor4_pressure: number;
    w7_reactor5_pressure: number;
    w7_reactor6_pressure: number;
    w7_reactor7_pressure: number;
    w7_reactor8_pressure: number;
    w7_reactor9_pressure: number;
    w7_reactor10_pressure: number;
    w7_reactor1_current: number;
    w7_reactor2_current: number;
    w7_reactor3_current: number;
    w7_reactor4_current: number;
    w7_reactor5_current: number;
    w7_reactor6_current: number;
    w7_reactor7_current: number;
    w7_reactor8_current: number;
    w7_reactor9_current: number;
    w7_reactor10_current: number;
    w7_steam_instant: number;
    w7_steam_total: number;
    w8_reactor1_pressure: number;
    w8_reactor2_pressure: number;
    w8_reactor3_pressure: number;
    w8_reactor4_pressure: number;
    w8_reactor1_current: number;
    w8_reactor2_current: number;
    w8_reactor3_current: number;
    w8_reactor4_current: number;
    w8_steam_instant: number;
    w8_steam_total: number;
    w8_old_steam_instant: number;
    w8_old_steam_total: number;
    w8_hg_steam_instant: number;
    w8_hg_steam_total: number;
    w8_output: number;
}

export interface AlarmData {
    [key: string]: boolean;
}

export interface Alarm {
    id: number;
    alarm_type: string;
    alarm_name: string;
    alarm_status: boolean;
    workshop_id?: string;
    workshop_name?: string;
    timestamp: string;
}

export const DEFAULT_DATA: ScadaData = {
    tank1_temp: 0,
    tank2_temp: 0,
    acid_flow_instant: 0,
    acid_flow_total: 0,
    waste_flow_instant: 0,
    waste_flow_total: 0,
    hcl_tank1_level: 0,
    hcl_tank2_level: 0,
    hcl_tank3_level: 0,
    hcl_tank4_level: 0,
    hcl_tank5_level: 0,
    h2so4_tank1_level: 0,
    leak1: 0,
    leak2: 0,
    leak3: 0,
    leak4: 0,
    loading_instant: 0,
    loading_total: 0,
    old_fan_v: 0,
    old_pump1_v: 0,
    old_pump2_v: 0,
    old_pump3_v: 0,
    drum_fan_v: 0,
    drum_pump1_v: 0,
    drum_pump2_v: 0,
    drum_centrifuge_v: 0,
    w3_underground1_temp: 0,
    w3_underground2_temp: 0,
    w3_underground3_temp: 0,
    w3_iron1_temp: 0,
    w3_iron2_temp: 0,
    w3_iron1_pressure: 0,
    w3_iron2_pressure: 0,
    w3_iron1_current: 0,
    w3_iron2_current: 0,
    w3_glass1_temp: 0,
    w3_glass2_temp: 0,
    w3_glass3_temp: 0,
    w3_glass4_temp: 0,
    w3_glass5_temp: 0,
    w3_glass1_current: 0,
    w3_glass2_current: 0,
    w3_glass3_current: 0,
    w3_glass4_current: 0,
    w3_glass5_current: 0,
    w3_enamel1_temp: 0,
    w3_enamel2_temp: 0,
    w3_enamel3_temp: 0,
    w3_enamel4_temp: 0,
    w3_enamel5_temp: 0,
    w3_enamel6_temp: 0,
    w3_enamel1_pressure: 0,
    w3_enamel2_pressure: 0,
    w3_enamel3_pressure: 0,
    w3_enamel4_pressure: 0,
    w3_enamel5_pressure: 0,
    w3_enamel6_pressure: 0,
    w3_enamel1_current: 0,
    w3_enamel2_current: 0,
    w3_enamel3_current: 0,
    w3_enamel4_current: 0,
    w3_enamel5_current: 0,
    w3_enamel6_current: 0,
    w3_poly_tail_fan_v: 0,
    w3_poly_tail_pump1_v: 0,
    w3_poly_tail_pump2_v: 0,
    w3_lowiron_tail_fan_v: 0,
    w3_lowiron_tail_pump1_v: 0,
    w3_lowiron_tail_pump2_v: 0,
    w3_steam_instant: 0,
    w3_steam_total: 0,
    w3_lowiron_steam_instant: 0,
    w3_lowiron_steam_total: 0,
    w3_loading_instant: 0,
    w3_loading_total: 0,
    w3_alkali_instant: 0,
    w3_alkali_total: 0,
    w3_iron_flow_instant: 0,
    w3_iron_flow_total: 0,
    w3_hcl_flow_instant: 0,
    w3_hcl_flow_total: 0,
    w4_reactor1_temp: 0,
    w4_reactor2_temp: 0,
    w4_reactor3_temp: 0,
    w4_reactor4_temp: 0,
    w4_reactor5_temp: 0,
    w4_reactor6_temp: 0,
    w4_reactor1_pressure: 0,
    w4_reactor2_pressure: 0,
    w4_reactor3_pressure: 0,
    w4_reactor4_pressure: 0,
    w4_reactor5_pressure: 0,
    w4_reactor6_pressure: 0,
    w4_reactor1_current: 0,
    w4_reactor2_current: 0,
    w4_reactor3_current: 0,
    w4_reactor4_current: 0,
    w4_reactor5_current: 0,
    w4_reactor6_current: 0,
    w4_fubang_khs_instant: 0,
    w4_fubang_khs_total: 0,
    w4_fubang_hcl_instant: 0,
    w4_fubang_hcl_total: 0,
    w4_output_packaging: 0,
    w5_reactor1_temp: 0,
    w5_reactor2_temp: 0,
    w5_reactor3_temp: 0,
    w5_reactor4_temp: 0,
    w5_reactor5_temp: 0,
    w5_reactor6_temp: 0,
    w5_reactor1_pressure: 0,
    w5_reactor2_pressure: 0,
    w5_reactor3_pressure: 0,
    w5_reactor4_pressure: 0,
    w5_reactor5_pressure: 0,
    w5_reactor6_pressure: 0,
    w5_reactor1_current: 0,
    w5_reactor2_current: 0,
    w5_reactor3_current: 0,
    w5_reactor4_current: 0,
    w5_reactor5_current: 0,
    w5_reactor6_current: 0,
    w5_output1: 0,
    w5_output2: 0,
    w6_dilute_sulfuric_level: 0,
    w6_sulfuric1_level: 0,
    w6_sulfuric2_level: 0,
    w6_sulfuric3_level: 0,
    w6_sulfuric4_level: 0,
    w6_sulfuric5_level: 0,
    w6_sulfuric6_level: 0,
    w6_sulfuric7_level: 0,
    w6_hcl1_level: 0,
    w6_hcl2_level: 0,
    w6_underground_level: 0,
    w6_kettle1_pressure: 0,
    w6_kettle2_pressure: 0,
    w6_kettle3_pressure: 0,
    w6_kettle4_pressure: 0,
    w6_kettle1_temp: 0,
    w6_kettle2_temp: 0,
    w6_kettle3_temp: 0,
    w6_kettle4_temp: 0,
    w6_kettle1_oxygen_flow: 0,
    w6_kettle2_oxygen_flow: 0,
    w6_kettle3_oxygen_flow: 0,
    w6_kettle4_oxygen_flow: 0,
    w6_loading1_instant: 0,
    w6_loading1_total: 0,
    w6_loading2_instant: 0,
    w6_loading2_total: 0,
    w6_batch1_instant: 0,
    w6_batch1_total: 0,
    w6_batch2_instant: 0,
    w6_batch2_total: 0,
    w6_loading1_once: 0,
    w6_loading2_once: 0,
    w6_batch1_once: 0,
    w6_batch2_once: 0,
    w6_kettle1_link_feed_open: 0,
    w6_kettle1_link_feed_closed: 0,
    w6_kettle2_link_feed_open: 0,
    w6_kettle2_link_feed_closed: 0,
    w6_kettle3_link_feed_open: 0,
    w6_kettle3_link_feed_closed: 0,
    w6_kettle4_link_feed_open: 0,
    w6_kettle4_link_feed_closed: 0,
    w6_kettle1_feed_open: 0,
    w6_kettle1_feed_closed: 0,
    w6_kettle2_feed_open: 0,
    w6_kettle2_feed_closed: 0,
    w6_kettle3_feed_open: 0,
    w6_kettle3_feed_closed: 0,
    w6_kettle4_feed_open: 0,
    w6_kettle4_feed_closed: 0,
    w6_kettle1_discharge_open: 0,
    w6_kettle1_discharge_closed: 0,
    w6_kettle2_discharge_open: 0,
    w6_kettle2_discharge_closed: 0,
    w6_kettle3_discharge_open: 0,
    w6_kettle3_discharge_closed: 0,
    w6_kettle4_discharge_open: 0,
    w6_kettle4_discharge_closed: 0,
    w6_kettle1_catalyst_open: 0,
    w6_kettle1_catalyst_closed: 0,
    w6_kettle2_catalyst_open: 0,
    w6_kettle2_catalyst_closed: 0,
    w6_kettle3_catalyst_open: 0,
    w6_kettle3_catalyst_closed: 0,
    w6_kettle4_catalyst_open: 0,
    w6_kettle4_catalyst_closed: 0,
    w6_kettle1_oxygen_open: 0,
    w6_kettle2_oxygen_open: 0,
    w6_kettle3_oxygen_open: 0,
    w6_kettle4_oxygen_open: 0,
    w7_reactor1_temp: 0,
    w7_reactor2_temp: 0,
    w7_reactor3_temp: 0,
    w7_reactor4_temp: 0,
    w7_reactor5_temp: 0,
    w7_reactor6_temp: 0,
    w7_reactor7_temp: 0,
    w7_reactor8_temp: 0,
    w7_reactor9_temp: 0,
    w7_reactor10_temp: 0,
    w7_reactor1_pressure: 0,
    w7_reactor2_pressure: 0,
    w7_reactor3_pressure: 0,
    w7_reactor4_pressure: 0,
    w7_reactor5_pressure: 0,
    w7_reactor6_pressure: 0,
    w7_reactor7_pressure: 0,
    w7_reactor8_pressure: 0,
    w7_reactor9_pressure: 0,
    w7_reactor10_pressure: 0,
    w7_reactor1_current: 0,
    w7_reactor2_current: 0,
    w7_reactor3_current: 0,
    w7_reactor4_current: 0,
    w7_reactor5_current: 0,
    w7_reactor6_current: 0,
    w7_reactor7_current: 0,
    w7_reactor8_current: 0,
    w7_reactor9_current: 0,
    w7_reactor10_current: 0,
    w7_steam_instant: 0,
    w7_steam_total: 0,
    w8_reactor1_pressure: 0,
    w8_reactor2_pressure: 0,
    w8_reactor3_pressure: 0,
    w8_reactor4_pressure: 0,
    w8_reactor1_current: 0,
    w8_reactor2_current: 0,
    w8_reactor3_current: 0,
    w8_reactor4_current: 0,
    w8_steam_instant: 0,
    w8_steam_total: 0,
    w8_old_steam_instant: 0,
    w8_old_steam_total: 0,
    w8_hg_steam_instant: 0,
    w8_hg_steam_total: 0,
    w8_output: 0,
};
